# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-06 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_serie', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('resume', models.CharField(max_length=100)),
                ('category_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
        ),
    ]
